spring.application.name=ReguLens

#DB configuration
spring.datasource.url= jdbc:postgresql://localhost:5432/ReguLens
spring.datasource.username=postgres
spring.datasource.password=qwerty12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/v1
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect